#!/bin/bash
# n1 -eq equal            n2 Возвращает истинное значение, если n1 равно n2.
# n1 -ge greater or equal n2 Возвращает истинное значение, если n1больше или равно n2.
# n1 -gt greater than     n2 Возвращает истинное значение, если n1 больше n2.
# n1 -le less or equal    n2 Возвращает истинное значение, если n1меньше или равно n2.
# n1 -lt less than        n2 Возвращает истинное значение, если n1 меньше n2.
# n1 -ne not equal n2 Возвращает истинное значение, если n1не равно n2
val1=11
if [ $val1 -gt 5 ]
then
echo "The test value $val1 is greater than 5"
else
echo "The test value $val1 is not greater than 5"
fi
