#!/bin/bash
# str1 = str2 Проверяет строки на равенство, возвращает истину, если строки идентичны.
# str1 != str2Возвращает истину, если строки не идентичны.
# str1 < str2Возвращает истину, если str1меньше, чем str2.
# str1 > str2 Возвращает истину, если str1больше, чем str2.
# -n str1 Возвращает истину, если длина str1больше нуля.
user="bdv"
if [ $user = $USER ]
then 
echo "The user $user us the current logged in user"
fi
