apiVersion: batch/v1
kind: CronJob
metadata:
  name: pi-cronjob
spec:
  schedule: "*/2 * * * *"  # Запуск каждые 2 минуты
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pi
            image: python:3.9
            command: ["python", "-c", "from math import pi; print(f'{pi:.20f}')"]
          restartPolicy: Never