apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: debug-4-ing
  namespace: debug-4
spec:
  ingressClassName: nginx
  rules:
  - host: debug-4.akj.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-svc
            port:
              number: 8000
         