apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: debug-6-ing
  namespace: debug-6
spec:
  ingressClassName: nginx
  rules:
  - host: debug-6.akj.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-svc
            port:
              number: 8000
         