apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: debug-2-ing
  namespace: debug-2
spec:
  ingressClassName: nginx
  rules:
  - host: debug-2.akj.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-svc
            port:
              number: 8000
         