workflow: 
  rules: 
    - if: $CI_COMMIT_BRANCH =~ /^feature\/.*$/
    - if: $CI_COMMIT_BRANCH =~ /^hotfix\/.*$/    
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_COMMIT_BRANCH =~ /^release\/(\d+\.\d+\.\d+)$/
    - if: $CI_COMMIT_TAG =~ /^(\d+\.\d+\.\d+)$/

stages:
  - build-and-push
  - test
  - deploy
  - deploy-prod

build-and-push:
  stage: build-and-push
  script: 
    - echo "This is a build-and-push stub"

unit-tests:
  stage: test
  script: 
    - echo "This is a unit-tests stub"

lint:
  stage: test
  script: 
    - echo "This is a lint stub"

deploy:
  stage: deploy
  script: 
    - echo "This is a deploy stub"

deploy-prod:
  stage: deploy-prod
  script: 
    - echo "This is a deploy-prod stub"    