apiVersion: v1
kind: Service
metadata:
  namespace: demo-lb
  name: goweb-svc-lb
spec:
  type: LoadBalancer
  selector:
    app: goapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
