apiVersion: batch/v1
kind: Job
metadata:
  name: echo-job
  namespace: home-dev 
spec:
  template:
    spec:
      containers:
      - name: echo
        image: busybox
        command: ["/bin/sh", "-c", "echo 'Hello, Kubernetes!'"]
      restartPolicy: Never
  backoffLimit: 4
