replicaCount: 1

image:
  repository: bdv21/payment-server
  tag: "0.0.1"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: payment-server-stage.akj.ru
      paths:
        - path: /
          pathType: ImplementationSpecific

resources: {}

envs:
  TEST_ENV: some-value