apiVersion: v1
kind: Service
metadata:
  namespace: demo-nodeport
  name: goweb-svc-nodeport
spec:
  type: NodePort
  selector:
    app: goapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8070
      nodePort: 30050